# Generated by Django 4.1.3 on 2022-11-22 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_crm', '0004_order_customer_order_product'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='tags',
            field=models.ManyToManyField(to='my_crm.tag'),
        ),
    ]
